//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.07 at 10:26:41 PM EET 
//


package com.company.homeworks.HW17.XML.modelsGen;

import javax.xml.bind.annotation.*;


@XmlRootElement(name = "Message")
@XmlAccessorType(XmlAccessType.FIELD)

public class MessageType {

    @XmlElement(name = "DateTime", required = true)
    protected String dateTime;
    @XmlElement(name = "CustomerId", required = true)
    protected String customerId;
    @XmlElement(name = "CompanyName", required = true)
    protected String companyName;
    @XmlElement(name = "CustomerNumber", required = true)
    protected String customerNumber;
    @XmlAttribute(name = "type")
    private String type;
    @XmlElement(name = "MessageDetails", required = true)
    protected MessageDetailsType messageDetails;
    @XmlElement(name = "Issues", required = true)
    protected IssuesType issues;

    public MessageType(String dateTime, String customerId, String companyName, String customerNumber, String type, MessageDetailsType messageDetails, IssuesType issues) {
        this.dateTime = dateTime;
        this.customerId = customerId;
        this.companyName = companyName;
        this.customerNumber = customerNumber;
        this.type = type;
        this.messageDetails = messageDetails;
        this.issues = issues;
    }

    public MessageType() {
    }

    public String getDateTime() {
        return dateTime;
    }

    public void setDateTime(String value) {
        this.dateTime = value;
    }

    public String getCustomerId() {
        return customerId;
    }

    public void setCustomerId(String value) {
        this.customerId = value;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String value) {
        this.companyName = value;
    }

    public String getCustomerNumber() {
        return customerNumber;
    }

    public void setCustomerNumber(String value) {
        this.customerNumber = value;
    }

    public MessageDetailsType getMessageDetails() {
        return messageDetails;
    }

    public void setMessageDetails(MessageDetailsType value) {
        this.messageDetails = value;
    }

    public IssuesType getIssues() {
        return issues;
    }

    public void setIssues(IssuesType value) {
        this.issues = value;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Override
    public String toString() {
        return "MessageType{" +
                "dateTime='" + dateTime + '\'' +
                ", customerId='" + customerId + '\'' +
                ", companyName='" + companyName + '\'' +
                ", customerNumber='" + customerNumber + '\'' +
                ", type='" + type + '\'' +
                ", messageDetails=" + messageDetails +
                ", issues=" + issues +
                '}';
    }
}
