//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.07 at 10:26:41 PM EET 
//


package com.company.homeworks.HW17.XML.modelsGen;

import javax.xml.bind.annotation.*;


@XmlAccessorType(XmlAccessType.FIELD)

public class MessageDetailsType {

    @XmlElement(name = "MessageId", required = true)
    protected String messageId;
    @XmlElement(name = "Datatype", required = true)
    protected String datatype;
    @XmlElement(name = "Type", required = true)
    protected String type;
    @XmlElement(name = "DatatypeDescription", required = true)
    protected String datatypeDescription;
    @XmlElement(name = "OriginalFilename", required = true)
    protected String originalFilename;

    public MessageDetailsType() {
    }

    public MessageDetailsType(String messageId, String datatype, String type, String datatypeDescription, String originalFilename) {
        this.messageId = messageId;
        this.datatype = datatype;
        this.type = type;
        this.datatypeDescription = datatypeDescription;
        this.originalFilename = originalFilename;
    }

    public String getMessageId() {
        return messageId;
    }

    public void setMessageId(String value) {
        this.messageId = value;
    }

    public String getDatatype() {
        return datatype;
    }

    public void setDatatype(String value) {
        this.datatype = value;
    }

    public String getTypeDet() {
        return type;
    }

    public void setTypeDet(String value) {
        this.type = value;
    }

    public String getDatatypeDescription() {
        return datatypeDescription;
    }

    public void setDatatypeDescription(String value) {
        this.datatypeDescription = value;
    }

    public String getOriginalFilename() {
        return originalFilename;
    }

    public void setOriginalFilename(String value) {
        this.originalFilename = value;
    }

    @Override
    public String toString() {
        return "MessageDetailsType{" +
                "messageId='" + messageId + '\'' +
                ", datatype='" + datatype + '\'' +
                ", type='" + type + '\'' +
                ", datatypeDescription='" + datatypeDescription + '\'' +
                ", originalFilename='" + originalFilename + '\'' +
                '}';
    }
}
